name: create_release

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths-ignore:
      - 'README.md'

jobs:
  create_release:
    runs-on: ubuntu-latest

    environment:
      name: dev

    steps:

    - name: Checkout code
      uses: actions/checkout@v4
      with:
        show-progress: 'false'
      
    - name: Generate version number
      id: tag_version
      uses: anothrNick/github-tag-action@1.70.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        DEFAULT_BUMP: patch

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ vars.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and Push Docker Image
      env:
        USERNAME: ${{ vars.DOCKERHUB_USERNAME }}
        REPOSITORY: splitcode
        IMAGE_NAME: splitcode
        TAG_LATEST: latest
        TAG_SEMVER: ${{ steps.tag_version.outputs.tag }}
        TAG_SHA: ${{ github.sha }}
      run: |
        set -e
        set -x
        docker build -t $IMAGE_NAME .
        docker tag $IMAGE_NAME $USERNAME/$REPOSITORY:$TAG_LATEST
        docker tag $IMAGE_NAME $USERNAME/$REPOSITORY:$TAG_SEMVER
        docker tag $IMAGE_NAME $USERNAME/$REPOSITORY:$TAG_SHA
        docker push $USERNAME/$REPOSITORY:$TAG_LATEST
        docker push $USERNAME/$REPOSITORY:$TAG_SEMVER
        docker push $USERNAME/$REPOSITORY:$TAG_SHA
        echo "::notice ::$USERNAME/$REPOSITORY:$TAG_SEMVER"

    - name: Create github release
      uses: ncipollo/release-action@v1
      with:
        tag: ${{ steps.tag_version.outputs.tag }}
        generateReleaseNotes: true